version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: priceadvisor-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pricing_db
      POSTGRES_USER: pricing_user
      POSTGRES_PASSWORD: pricing_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pricing_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pricing-net


  pgadmin:
    image: dpage/pgadmin4
    container_name: priceadvisor-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@priceadvisor.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - pricing-net

  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - "2181:2181"
    restart: always
    environment:
      JVMFLAGS: "-Xms1024m -Xmx2048m"
      ZOO_ENABLE_AUTH: "false"
    networks:
      - pricing-net

  kafka:
    image: confluentinc/cp-kafka:7.1.2
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper
    networks:
      - pricing-net

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    hostname: kafdrop
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:19092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka
    networks:
      - pricing-net

  pricing-api:
    image: pricing-api:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pricing_db
      - SPRING_DATASOURCE_USERNAME=pricing_user
      - SPRING_DATASOURCE_PASSWORD=pricing_pass
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:19092
    depends_on:
      - kafka
      - postgres
    networks:
      - pricing-net

volumes:
  postgres_data:

networks:
  pricing-net:
    external: true