app:
  currency: EUR
  kafka:
    topics:
      click-event-topic: click-event
      order-event-topic: order-event
      inventory-event-topic: inventory-event
      rule-event-topic: rule-event
      price-result-topic: pricing-results

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pricing_db
    username: ${DB_USERNAME:pricing_user}
    password: ${DB_PASSWORD:pricing_pass}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jooq:
    sql-dialect: postgres

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: pricing-api-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'


